// SPDX-FileCopyrightText: 2022 Mischback
// SPDX-License-Identifier: MIT
// SPDX-FileType: SOURCE

#ifndef SRC_LIB_WIFI_MANAGEMENT_INCLUDE_WIFI_MANAGEMENT_H_
#define SRC_LIB_WIFI_MANAGEMENT_INCLUDE_WIFI_MANAGEMENT_H_

void wifi_initialize(void);

#endif  // SRC_LIB_WIFI_MANAGEMENT_INCLUDE_WIFI_MANAGEMENT_H_
