version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Mischback"
    open-pull-requests-limit: 5

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/requirements/python"
    schedule:
      interval: "daily"
    assignees:
      - "Mischback"
    open-pull-requests-limit: 10
