// SPDX-FileCopyrightText: 2022 Mischback
// SPDX-License-Identifier: MIT
// SPDX-FileType: SOURCE

#ifndef SRC_LIB_EMBEDDED_AUDIOPLAYER_ESP32_INCLUDE_MAP32_MAP32_H_
#define SRC_LIB_EMBEDDED_AUDIOPLAYER_ESP32_INCLUDE_MAP32_MAP32_H_

#endif  // SRC_LIB_EMBEDDED_AUDIOPLAYER_ESP32_INCLUDE_MAP32_MAP32_H_
