// SPDX-FileCopyrightText: 2022 Mischback
// SPDX-License-Identifier: MIT
// SPDX-FileType: SOURCE

#ifndef SRC_LIB_NETWORKING_SRC_NETWORKING_WEB_H_
#define SRC_LIB_NETWORKING_SRC_NETWORKING_WEB_H_

#endif  // SRC_LIB_NETWORKING_SRC_NETWORKING_WEB_H_
