# SPDX-License-Identifier: MIT

name: CI Default Branch

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
#   linting:
#     name: Linting
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2
#       - name: Setup Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements/python/tox.txt
#       - name: Run cpplint
#         run: make util/cpplint
#       - name: Run black
#         run: make util/black
#       - name: Run flake8
#         run: make util/flake8

  building:
    name: Building
    # needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install System Dependencies
        # as per https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-macos-setup.html#for-linux-users
        run: |
          sudo apt-get install \
            git \
            wget \
            flex \
            bison \
            gperf \
            cmake \
            ninja-build \
            ccache \
            libffi-dev \
            libssl-dev \
            dfu-util \
            libusb-1.0-0
      - name: Setting Internal Variables
        run: |
          __REPO_DIR=`pwd`
          __IDF="${__REPO_DIR}/esp"
          echo "IDF_PATH=${__IDF}" >> ${GITHUB_ENV}
      - name: Get ESP-IDF
        uses: actions/checkout@v2
        with:
          repository: espressif/esp-idf
          path: esp
          submodules: recursive
          ref: v4.4.1
      - name: Run idf_tools.py install
        run: |
          ${IDF_PATH}/tools/idf_tools.py install
      - name: Run idf_tools.py install-python-env
        run: |
          ${IDF_PATH}/tools/idf_tools.py install-python-env
      - name: Build the Project
        run: |
          ${IDF_PATH}/tools/idf.py build

#   documentation:
    # name: Documentation
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout Code
    #     uses: actions/checkout@v2
    #   - name: Setup Python
    #     uses: actions/setup-python@v2
    #     with:
    #       python-version: 3.9
    #   - name: Install dependencies
    #     run: |
    #       sudo apt-get install doxygen
    #       python -m pip install --upgrade pip
    #       pip install -r requirements/python/tox.txt
    #   - name: Run Sphinx's linkcheck
    #     run: make sphinx/linkcheck
    #   - name: Build HTML Documentation
    #     run: make sphinx/build/html
